### ISSUE TITLE
Check necessary compilations flags that are interesting to keep as a reference.

### ISSUE THREAD

**Issue by williamjamir** [ESSS/hookman#13]
The PR https://github.com/ESSS/hookman/pull/12 removes the compilation flags used on cpp.

We need to check if we want to add some compilation flag for C/C++ builds as a "default" configuration.

@tadeu

**Comment by tadeu** [comment]
I think this issue may be close, we are as default as it can be, it there are any specific problems, a new issue may be opened (with the specific problems).
